stages:
  - deploy

Deployment:
  image: ruby:2.4
  stage: deploy
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=tes-todolist --api-key=46ed961e-054f-4f0f-8438-b09315e372b4
    - export HEROKU_API_KEY=46ed961e-054f-4f0f-8438-b09315e372b4
  environment:
    name: production
    url: https://tes-todolist.herokuapp.com/
  only:
    - master